/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthVerifyImport } from './routes/auth/verify'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AppProfileCreationImport } from './routes/app/profile-creation'
import { Route as AppProfileImport } from './routes/app/profile'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyRoute = AuthVerifyImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AppProfileCreationRoute = AppProfileCreationImport.update({
  id: '/app/profile-creation',
  path: '/app/profile-creation',
  getParentRoute: () => rootRoute,
} as any)

const AppProfileRoute = AppProfileImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileImport
      parentRoute: typeof rootRoute
    }
    '/app/profile-creation': {
      id: '/app/profile-creation'
      path: '/app/profile-creation'
      fullPath: '/app/profile-creation'
      preLoaderRoute: typeof AppProfileCreationImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/profile': typeof AppProfileRoute
  '/app/profile-creation': typeof AppProfileCreationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/profile': typeof AppProfileRoute
  '/app/profile-creation': typeof AppProfileCreationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app/profile': typeof AppProfileRoute
  '/app/profile-creation': typeof AppProfileCreationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/profile'
    | '/app/profile-creation'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/profile'
    | '/app/profile-creation'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
  id:
    | '__root__'
    | '/'
    | '/app/profile'
    | '/app/profile-creation'
    | '/auth/login'
    | '/auth/register'
    | '/auth/verify'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProfileCreationRoute: typeof AppProfileCreationRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppProfileRoute: AppProfileRoute,
  AppProfileCreationRoute: AppProfileCreationRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyRoute: AuthVerifyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app/profile",
        "/app/profile-creation",
        "/auth/login",
        "/auth/register",
        "/auth/verify"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app/profile": {
      "filePath": "app/profile.tsx"
    },
    "/app/profile-creation": {
      "filePath": "app/profile-creation.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/auth/verify": {
      "filePath": "auth/verify.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
