/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthVerifyImport } from './routes/auth/verify'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthNotVerifyImport } from './routes/auth/not-verify'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as AppSearchImport } from './routes/app/search'
import { Route as AppMatchImport } from './routes/app/match'
import { Route as AppProfileIndexImport } from './routes/app/profile/index'
import { Route as AppProfileCreationImport } from './routes/app/profile/creation'
import { Route as AppProfileUsernameImport } from './routes/app/profile/$username'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthVerifyRoute = AuthVerifyImport.update({
  id: '/auth/verify',
  path: '/auth/verify',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthNotVerifyRoute = AuthNotVerifyImport.update({
  id: '/auth/not-verify',
  path: '/auth/not-verify',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const AppSearchRoute = AppSearchImport.update({
  id: '/app/search',
  path: '/app/search',
  getParentRoute: () => rootRoute,
} as any)

const AppMatchRoute = AppMatchImport.update({
  id: '/app/match',
  path: '/app/match',
  getParentRoute: () => rootRoute,
} as any)

const AppProfileIndexRoute = AppProfileIndexImport.update({
  id: '/app/profile/',
  path: '/app/profile/',
  getParentRoute: () => rootRoute,
} as any)

const AppProfileCreationRoute = AppProfileCreationImport.update({
  id: '/app/profile/creation',
  path: '/app/profile/creation',
  getParentRoute: () => rootRoute,
} as any)

const AppProfileUsernameRoute = AppProfileUsernameImport.update({
  id: '/app/profile/$username',
  path: '/app/profile/$username',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/app/match': {
      id: '/app/match'
      path: '/app/match'
      fullPath: '/app/match'
      preLoaderRoute: typeof AppMatchImport
      parentRoute: typeof rootRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/app/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/not-verify': {
      id: '/auth/not-verify'
      path: '/auth/not-verify'
      fullPath: '/auth/not-verify'
      preLoaderRoute: typeof AuthNotVerifyImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/auth/verify': {
      id: '/auth/verify'
      path: '/auth/verify'
      fullPath: '/auth/verify'
      preLoaderRoute: typeof AuthVerifyImport
      parentRoute: typeof rootRoute
    }
    '/app/profile/$username': {
      id: '/app/profile/$username'
      path: '/app/profile/$username'
      fullPath: '/app/profile/$username'
      preLoaderRoute: typeof AppProfileUsernameImport
      parentRoute: typeof rootRoute
    }
    '/app/profile/creation': {
      id: '/app/profile/creation'
      path: '/app/profile/creation'
      fullPath: '/app/profile/creation'
      preLoaderRoute: typeof AppProfileCreationImport
      parentRoute: typeof rootRoute
    }
    '/app/profile/': {
      id: '/app/profile/'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/match': typeof AppMatchRoute
  '/app/search': typeof AppSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/not-verify': typeof AuthNotVerifyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/profile/$username': typeof AppProfileUsernameRoute
  '/app/profile/creation': typeof AppProfileCreationRoute
  '/app/profile': typeof AppProfileIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/match': typeof AppMatchRoute
  '/app/search': typeof AppSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/not-verify': typeof AuthNotVerifyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/profile/$username': typeof AppProfileUsernameRoute
  '/app/profile/creation': typeof AppProfileCreationRoute
  '/app/profile': typeof AppProfileIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/app/match': typeof AppMatchRoute
  '/app/search': typeof AppSearchRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/not-verify': typeof AuthNotVerifyRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/verify': typeof AuthVerifyRoute
  '/app/profile/$username': typeof AppProfileUsernameRoute
  '/app/profile/creation': typeof AppProfileCreationRoute
  '/app/profile/': typeof AppProfileIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/match'
    | '/app/search'
    | '/auth/login'
    | '/auth/not-verify'
    | '/auth/register'
    | '/auth/verify'
    | '/app/profile/$username'
    | '/app/profile/creation'
    | '/app/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/match'
    | '/app/search'
    | '/auth/login'
    | '/auth/not-verify'
    | '/auth/register'
    | '/auth/verify'
    | '/app/profile/$username'
    | '/app/profile/creation'
    | '/app/profile'
  id:
    | '__root__'
    | '/'
    | '/app/match'
    | '/app/search'
    | '/auth/login'
    | '/auth/not-verify'
    | '/auth/register'
    | '/auth/verify'
    | '/app/profile/$username'
    | '/app/profile/creation'
    | '/app/profile/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppMatchRoute: typeof AppMatchRoute
  AppSearchRoute: typeof AppSearchRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthNotVerifyRoute: typeof AuthNotVerifyRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthVerifyRoute: typeof AuthVerifyRoute
  AppProfileUsernameRoute: typeof AppProfileUsernameRoute
  AppProfileCreationRoute: typeof AppProfileCreationRoute
  AppProfileIndexRoute: typeof AppProfileIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppMatchRoute: AppMatchRoute,
  AppSearchRoute: AppSearchRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthNotVerifyRoute: AuthNotVerifyRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthVerifyRoute: AuthVerifyRoute,
  AppProfileUsernameRoute: AppProfileUsernameRoute,
  AppProfileCreationRoute: AppProfileCreationRoute,
  AppProfileIndexRoute: AppProfileIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/app/match",
        "/app/search",
        "/auth/login",
        "/auth/not-verify",
        "/auth/register",
        "/auth/verify",
        "/app/profile/$username",
        "/app/profile/creation",
        "/app/profile/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/app/match": {
      "filePath": "app/match.tsx"
    },
    "/app/search": {
      "filePath": "app/search.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/not-verify": {
      "filePath": "auth/not-verify.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/auth/verify": {
      "filePath": "auth/verify.tsx"
    },
    "/app/profile/$username": {
      "filePath": "app/profile/$username.tsx"
    },
    "/app/profile/creation": {
      "filePath": "app/profile/creation.tsx"
    },
    "/app/profile/": {
      "filePath": "app/profile/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
